// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:298dbfcd-201b-407d-a0c3-61d5ed25b015",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_gVJJUFhJX",
    "aws_user_pools_web_client_id": "3pji584n60lklqt0qsc75canl",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://772zhx6ymvcanlfecda62ljzme.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
